# Generated by Django 5.2.5 on 2025-09-03 07:37

from django.db import migrations


def set_new_building_status(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
        elif flat.construction_year:
            flat.new_building = False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_status),
    ]
