# Generated by Django 5.2.5 on 2025-09-03 10:37

from django.db import migrations
from phonenumbers import parse, format_number, PhoneNumberFormat
from phonenumbers import NumberParseException


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_number = parse(flat.owners_phonenumber, 'RU')
                normalized_number = format_number(parsed_number, PhoneNumberFormat.E164)
                flat.owner_pure_phone = normalized_number
                flat.save()
            except NumberParseException:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
