# Generated by Django 5.2.5 on 2025-09-04 09:03

from django.db import migrations


def set_owner_flat_relations(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    for flat in Flat.objects.all().iterator():
        owner = Owner.objects.filter(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber
        ).first()
        
        if owner:
            owner.flats.add(flat)

def reverse_func(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        owner.flats.clear()

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_create_owners'),
    ]

    operations = [
        migrations.RunPython(set_owner_flat_relations, reverse_func),
    ]