# Generated by Django 5.2.6 on 2025-09-08 08:41

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО владельца (временное)'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер владельца (временное)'),
        ),
    ]