# Generated by Django 5.2.6 on 2025-09-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
        ('property', '0015_add_temp_fields'),
    ]

    operations = [
    ]
